accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'sign_in/$', views.sign_in, name='sign_in'),
    url(r'sign_up/$', views.sign_up, name='sign_up'),
    url(r'sign_out/$', views.sign_out, name='sign_out'),
    url(r'edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'profile/detail/(?P<user_pk>\d+)/$', views.profile, name='profile'),
    url(r'profile/change_password/$',
        views.change_password,
        name='change_password'),
    url(r'ajax/load-cities/$', views.load_cities, name='ajax_load_cities'),
]

project_7/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', views.home, name='home'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
import os
import random

from cities_light.models import Country, City
from ckeditor.fields import RichTextField


class Profile(models.Model):
    """Model describing dditional info related to each user
    """
    def get_avatar():
        path = settings.MEDIA_ROOT + '/owls'
        files = os.listdir(path)
        index = random.randint(0, len(files) - 1)
        return 'owls/' + files[index]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField(null=True)
    bio = RichTextField(blank=True, null=True)
    avatar = models.ImageField(default=get_avatar, upload_to='avatars')
    CAT = 'Cats'
    DOG = 'Dogs'
    CHOICES = (
        (CAT, 'Cats'),
        (DOG, 'Dogs')
    )
    cats_or_dogs = models.CharField(max_length=4, choices=CHOICES, default=DOG)
    favourite_colour = models.CharField(max_length=32, blank=True, null=True)
    hobby = models.CharField(max_length=32, blank=True, null=True)
    country = models.ForeignKey(Country, blank=True, null=True)
    city = models.ForeignKey(City, blank=True, null=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm,
                                       UserChangeForm)
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from django.shortcuts import get_object_or_404

from .models import Profile, City

import re


class ProfileForm(forms.ModelForm):
    """Form describing additonal user details 
    """
    date_of_birth = forms.DateField(
        input_formats=('%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y',)
    )

    class Meta:
        model = Profile
        fields = [
            'date_of_birth',
            'bio',
            'cats_or_dogs',
            'favourite_colour',
            'hobby',
            'country',
            'city',
        ]

    def __init__(self, *args, **kwargs):
        """Changing init to clear out Cities options in select field so 
        we can first get Country selection and then re-populate Cities 
        based on the selected Country
        """
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(
                    country_id=country_id
                ).order_by('name')
            except (ValueError, TypeError):
                pass 
        elif self.instance.pk:
            self.fields['city'].queryset = City.objects.filter(
                country_id=(1, 2)
            ).order_by('name')


    class Media:
        css = {'all': ('css/bootstrap-datepicker3.standalone.css',)}
        js = (
            'js/bootstrap.bundle.min.js',
            'js/bootstrap-datepicker.js',
            )

    def clean_bio(self):
        """Ensure that bio info is greater than 10 and less than 1000
        characters
        """
        value = self.cleaned_data['bio']
        if len(value) < 10:
            raise forms.ValidationError(
                "We want to know you better! (10 characters or greater)")
        if len(value) > 1000:
            raise forms.ValidationError("Ok whoa, TMI! (1000 characters max)")
        return value
    
   
class AvatarForm(forms.ModelForm):
    """Form holding the user's avatar. We're using a separate form so 
    cropperjs can update outside of the other user data
    """
    class Meta:
        model = Profile
        fields = [
            'avatar',
        ]

    class Media:
        css = {'all': ('cropperjs/dist/cropper.css',)}
        js = ('cropperjs/dist/cropper.js',
              'jquery-cropper/dist/jquery-cropper.js',
              )


class UserForm(forms.Form):
    """Form that describes the user model (inherits from the standard 
    Django user model)
    """
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(UserForm, self).__init__(*args, **kwargs)

    first_name = forms.CharField(max_length=56)
    last_name = forms.CharField(max_length=56)
    email = forms.EmailField(max_length=56)
    email2 = forms.EmailField(max_length=56, label="Email Confirmation")

    def clean(self):
        """Ensure both user emails match
        """
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        email2 = cleaned_data.get('email2')

        if email != email2:
            msg = "Both emails must match."
            self.add_error('email2', msg)


class ChangePasswordForm(forms.Form):
    """Form to validate and change user's password
    """
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    password_help_text = {
        'same': 'must not be the same as the current password',
        'length': 'minimum password length of 14 characters',
        'lowercase': 'must contain lowercase letters',
        'uppercase': 'must contain uppercase letters',
        'digit': 'must include one or more numerical digits',
        'at': 'must contain @ sign',
        'pound': 'must contain # sign',
        'dollar': 'must contain $ sign',
        'username': 'cannot contain your username',
        'firstname': 'cannot contain your first name',
        'lastname': 'cannot contain your last name',
    }

    old_password = forms.CharField(label='Old password:',
                                   widget=forms.PasswordInput
                                   )
    new_password = forms.CharField(
        label='New password:',
        widget=forms.PasswordInput,
        help_text=password_help_text.values(),
        )                              
    new_password2 = forms.CharField(label='New password confirmation:',
                                    widget=forms.PasswordInput
                                    )

    def clean_old_password(self):
        """validate existing password
        """
        old_password = self.cleaned_data['old_password']
        if not self.user.check_password(old_password):
            raise forms.ValidationError("Your old password is incorrect!")
        return old_password

    def clean(self):
        """validate new passwords against valid regex patterns
        """
        cleaned_data = super().clean()
        old_pass = cleaned_data.get('old_password')
        new_pass = cleaned_data.get('new_password')
        new_pass2 = cleaned_data.get('new_password2')

        # passord should contain following
        if re.search(r'[a-z]', new_pass) == None:
            msg = self.password_help_text['lowercase']
            self.add_error('new_password', msg)

        if re.search(r'[A-Z]', new_pass) == None:
            msg = self.password_help_text['uppercase']
            self.add_error('new_password', msg)

        if re.search(r'[0-9]', new_pass) == None:
            msg = self.password_help_text['digit']
            self.add_error('new_password', msg)
        
        if re.search(r'@', new_pass) == None:
            msg = self.password_help_text['at']
            self.add_error('new_password', msg)

        if re.search(r'#', new_pass) == None:
            msg = self.password_help_text['pound']
            self.add_error('new_password', msg)

        if re.search(r'\$', new_pass) == None:
            msg = self.password_help_text['dollar']
            self.add_error('new_password', msg)

        #password should not contain following
        if re.search(r'{}'.format(self.user.username), new_pass, re.I) is not None:
            msg = self.password_help_text['username']
            self.add_error('new_password', msg)

        if re.search(r'{}'.format(self.user.first_name), new_pass, re.I) is not None:
            if self.user.first_name != "":
                print("first name: ", self.user.first_name)
                msg = self.password_help_text['firstname']
                self.add_error('new_password', msg)
        
        if re.search(r'{}'.format(self.user.last_name), new_pass, re.I) is not None:
            if self.user.last_name != "":
                msg = self.password_help_text['lastname']
                self.add_error('new_password', msg)

        if new_pass == old_pass:
            raise forms.ValidationError(
                "Your new password can't be your old password!"
            )

        if new_pass != new_pass2:
            raise forms.ValidationError("Your new passwords don't match!")

        if len(new_pass) < 14:
            msg = "Your new password must be minimum 14 characters."
            self.add_error('new_password', msg)
    

accounts/views.py
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm,
                                       UserChangeForm)
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.defaultfilters import pluralize

from .forms import ProfileForm, UserForm, ChangePasswordForm, AvatarForm
from .models import Profile, User, City


def sign_in(request):
    """View that handles user sign-in and redirects to next or their 
    profile
    """
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    next_url = request.POST.get(
                        'next',
                        reverse('accounts:profile', 
                        kwargs={'user_pk': user.pk})
                    )
                    messages.success(
                        request, f'Welcome back, {user.username}!')
                    return HttpResponseRedirect(next_url)
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    """View that handles user sign-up and redirects to user's incomplete 
    profile
    """
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            Profile.objects.create(user=user)
            login(request, user)
            messages.success(
                request,
                "You're now a user! You've been signed in, too."
            )
            return HttpResponseRedirect(reverse('accounts:profile',
                                                kwargs={'user_pk': user.id})
                                        )
        messages.error(request, "Something went wrong!")
        return render(request, 'accounts/sign_up.html', {'form': form})
    return render(request, 'accounts/sign_up.html', {'form': form})


@login_required
def edit_profile(request):
    """View that handles the editing of the request user's profile. 
    This is donethrough data received by the user_form, profile_form, 
    and the avatar_form (the avatar form is accepted as an ajax post).
    """
    user = request.user
    existing_data = {
        'first_name': user.first_name,
        'last_name': user.last_name,
        'email': user.email,
    }
    user_form = UserForm(data=existing_data, user=user)
    profile = get_object_or_404(Profile, user=user)
    profile_form = ProfileForm(instance=profile)
    avatar_form = AvatarForm(instance=profile)

    if request.method == 'POST':
        user_form = UserForm(data=request.POST, user=user)
        profile_form = ProfileForm(
            request.POST, request.FILES, instance=profile)
        if user_form.is_valid() and profile_form.is_valid():
            cleaned = user_form.cleaned_data
            user.first_name = cleaned['first_name']
            user.last_name = cleaned['last_name']
            user.email = cleaned['email']
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            messages.success(request, 'Profile updated successfully!')
            return HttpResponseRedirect(reverse('accounts:profile',
                                                kwargs={'user_pk': user.id})
                                        )
        avatar_form = AvatarForm(request.POST, request.FILES, instance=profile)
        if avatar_form.is_valid() and request.is_ajax():
            profile.avatar = request.FILES['id_avatar']
            profile.save()

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'avatar_form': avatar_form,
        'user': user,
    }
    return render(request, 'accounts/edit_profile.html', context)


@login_required
def change_password(request):
    """View that handles changing the user's password. Success redirects 
    user to their profile.
    """
    user = request.user
    password_form = ChangePasswordForm(user=user)
    if request.method == 'POST':
        password_form = ChangePasswordForm(user=user, data=request.POST)
        if password_form.is_valid():
            new_password = password_form.cleaned_data['new_password']
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, password_form.user)
            messages.success(request, "Password changed successfully!")
            return HttpResponseRedirect(reverse('accounts:profile', 
                                                kwargs={'user_pk': user.id}))
    context = {
        'password_form': password_form,
        'user': user,
    }
    return render(request, 'accounts/change_password.html', context)


def profile(request, user_pk):
    """View that handles the detail view of the user and the user's 
    profile
    """
    profile_user = get_object_or_404(User, pk=user_pk)
    profile = get_object_or_404(Profile, user=profile_user)
    if request.user == profile_user:
        missing = 0 #inform the user of empty profile fields
        for field in profile._meta.fields:
            field_value = field.value_from_object(profile)
            if not field_value and field_value != 0:
                missing += 1
        for field in profile_user._meta.fields:
            field_value = field.value_from_object(profile_user)
            if not field_value and field_value != 0:
                missing += 1
        if missing:
            messages.warning(
                request,
                f'''{missing} field{pluralize(missing)} in your profile 
                {pluralize(missing, "is,are")} missing!
                ''') # using the pluralize template filter directly in the view

    return render(request, 'accounts/profile.html', {'profile_user': profile_user})


def sign_out(request):
    """View handling the user's sign out and redirecting to the home 
    page
    """
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


def load_cities(request):
    """When the edit profile view is loaded, cities are emitted from the 
    options until a country is selected. When a country is selected, an 
    ajax request to this view will return a list of cities (back to the 
    edit profile template) filtered by the selected country  
    """
    country_code = request.GET.get('country')
    cities = City.objects.filter(country_id=country_code).order_by('name')
    return render(
        request,
        'accounts/city_dropdown_list_options.html',
        {'cities': cities}
    )

accounts/templates/accounts/edit_profile.html
{% extends "layout.html" %} 
{% load static %} 
{% block title %}Profile |{{ super }}{% endblock %} 

{% block body %}
<div class="bounds circle--page profile_page">
    <form method="POST" id="userform_and_profileform" data-cities-url="{% url 'accounts:ajax_load_cities' %}"
        enctype="multipart/form-data" action="">
        {% csrf_token %}
        <div class="avatar_wrapper">
            <span class="avatar_base avatar_update">
                <label class="label" data-toggle="tooltip" title="" data-original-title="Change">
                    <img name="id_avatar" id="id_avatar" class="avatar_circle" src="{{ user.profile.avatar.url }}"
                        alt="avatar" />
                    <input type="file" class="sr-only" id="input" name="image" accept="image/*" hidden="True">
                    <p>Change</p>
                </label>
        </div>

        <div class="grid-100 under_banner">
            {{ user.first_name.label }}
            <h1 class="headline">{{ user.username }}</h1>
        </div>

        <div class="grid-30">
            <p>
                {{ user_form.first_name.errors }}
                {{ user_form.first_name.label }}
                {{ user_form.first_name }}
            </p>
            <p>
                {{ user_form.last_name.errors }}
                {{ user_form.last_name.label }}
                {{ user_form.last_name }}
            </p>
            <p>
                {{ user_form.email.errors }}
                {{ user_form.email.label }}
                {{ user_form.email }}
            </p>
            <p>
                {{ user_form.email2.errors }}
                {{ user_form.email2.label }}
                {{ user_form.email2 }}
            </p>
            <p>
                {{ profile_form.date_of_birth.errors }}
                {{ profile_form.date_of_birth.label }}
                {{ profile_form.date_of_birth }}
            </p>
           
            <p>
                {{ profile_form.country.errors }}
                {{ profile_form.country.label }}
                {{ profile_form.country }}
            </p>
            <p>
                {{ profile_form.city.errors }}
                {{ profile_form.city.label }}
                {{ profile_form.city }}
            </p>         
        </div>

        <div class="grid-70">
            {{ profile_form.bio.label }}
            <div class="bio_wrapper">
                {{ profile_form.bio.errors }}
                {{ profile_form.bio }}
            </div>
            <p>
                {{ profile_form.cats_or_dogs.errors }}
                {{ profile_form.cats_or_dogs.label }}
                {{ profile_form.cats_or_dogs }}
            </p>
            <p>
                {{ profile_form.hobby.errors }}
                {{ profile_form.hobby.label }}
                {{ profile_form.hobby }}
            </p>
            <p>
                {{ profile_form.favourite_colour.errors }}
                {{ profile_form.favourite_colour.label }}
                {{ profile_form.favourite_colour }}
            </p>

            <input type="submit" class="button-primary" value="Update Profile" />
            <a href="{% url 'accounts:change_password' %}" class="button button-info">Change Password</a>
        </div>
</div>
</form>
</div>

<!--avatar modal start-->
<div class="modal_container">
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel">Crop the image</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="img-container">
                        <img id="image" src="{{ user.profile.avatar.url }}">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="button-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="button-primary" id="crop">Crop</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!--avatar modal end-->

{% endblock %}
<br />
{% block css %}
{{ profile_form.media.css }}
{{ avatar_form.media.css }}
{% endblock %}
<br />
{% block javascript %}
{{ profile_form.media.js }}
{{ avatar_form.media.js }}
<script type="text/javascript">
    // Datepicker js
    $("#id_date_of_birth").datepicker({
        autoclose: true,
        orientation: "left bottom",
        forceParse: false,
        width: '50px',
    });
</script>

<script type="text/javascript">

    window.addEventListener('DOMContentLoaded', function () {
        var avatar = document.getElementById('id_avatar');
        var image = document.getElementById('image');
        var input = document.getElementById('input');
        var $progress = $('.progress');
        var $progressBar = $('.progress-bar');
        var $alert = $('.alert');
        var $modal = $('#modal');
        var cropper;

        input.addEventListener('change', function (e) {
            var files = e.target.files;
            var done = function (url) {
                input.value = '';
                image.src = url;
                $alert.hide();
                $modal.modal('show');
            };
            var reader;
            var file;
            var url;

            if (files && files.length > 0) {
                file = files[0];

                if (URL) {
                    done(URL.createObjectURL(file));
                } else if (FileReader) {
                    reader = new FileReader();
                    reader.onload = function (e) {
                        done(reader.result);
                    };
                    reader.readAsDataURL(file);
                }
            }
        });

        $modal.on('shown.bs.modal', function () {
            cropper = new Cropper(image, {
                aspectRatio: 1,
                viewMode: 3,
            });
        }).on('hidden.bs.modal', function () {
            cropper.destroy();
            cropper = null;
        });

        document.getElementById('crop').addEventListener('click', function () {
            var initialAvatarURL;
            var canvas;

            $modal.modal('hide');

            if (cropper) {
                canvas = cropper.getCroppedCanvas({
                    width: 450,
                    height: 450,
                });
                initialAvatarURL = avatar.src;
                avatar.src = canvas.toDataURL('image/jpeg', 1);
                $progress.show();
                $alert.removeClass('alert-success alert-warning');
                canvas.toBlob(function (blob) {
                    var formData = new FormData();

                    function getCookie(name) {
                        var cookieValue = null;
                        if (document.cookie && document.cookie !== '') {
                            var cookies = document.cookie.split(';');
                            for (var i = 0; i < cookies.length; i++) {
                                var cookie = cookies[i].trim();
                                // Does this cookie string begin with the name we want?
                                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                    break;
                                }
                            }
                        }
                        return cookieValue;
                    }
                    var csrftoken = getCookie('csrftoken');

                    function csrfSafeMethod(method) {
                        // these HTTP methods do not require CSRF protection
                        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                    }


                    formData.append('id_avatar', blob, 'new_avatar.jpg');
                    $.ajaxSetup({
                        beforeSend: function (xhr, settings) {
                            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                            }
                        }
                    });

                    $.ajax('', {
                        method: 'POST',
                        data: formData,
                        processData: false,
                        contentType: false,


                        xhr: function () {
                            var xhr = new XMLHttpRequest();

                            xhr.upload.onprogress = function (e) {
                                var percent = '0';
                                var percentage = '0%';

                                if (e.lengthComputable) {
                                    percent = Math.round((e.loaded / e.total) * 100);
                                    percentage = percent + '%';
                                    $progressBar.width(percentage).attr('aria-valuenow', percent).text(percentage);
                                }
                            };

                            return xhr;
                        },

                        success: function () {
                            $alert.show().addClass('alert-success').text('Avatar uploaded successfully!');
                        },

                        error: function () {
                            avatar.src = initialAvatarURL;
                            $alert.show().addClass('alert-warning').text('Error uploading avatar!');
                        },

                        complete: function () {
                            $progress.hide();
                        },
                    });
                });
            }
        });
    });

</script>


<script type="text/javascript">
    $(document).ready(function () {
        $('#alert').on('click', function () {
            $('#alert').hide();
        });
    });
</script>

<script>
    $("#id_country").change(function () {
        var url = $("#userform_and_profileform").attr("data-cities-url");  // get the url of the `load_cities` view
        var countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'country': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends "layout.html" %} 
{% load static %} 
{% block title %}Profile |{{ super }}{% endblock %} 

{% block body %}
<div class="bounds circle--page profile_page">
    <div class="avatar_wrapper">
        <span class="avatar_base">
            <img class="avatar_circle" src="{{ profile_user.profile.avatar.url }}" />
        </span>
    </div>
    <div class="grid-100 under_banner">
        {{ profile_user.first_name.label }}
        <h1 class="headline">{{ profile_user.username|capfirst }}</h1>
    </div>

    <div class="grid-30">
        <h1 class="custom_label">Details</h1>
        <br>
        <p>
            Name:
            {{ profile_user.first_name }}
            {{ profile_user.last_name }}
            <br>
            Date of Birth:
            {{ profile_user.profile.date_of_birth }}
            <br>
            Location:
            {% firstof profile_user.profile.city profile_user.profile.country "Unknown" %}
        </p>
        <hr>

        <h1 class="custom_label">Contact</h1>
        <br>
        <p>
            Email: {{ profile_user.email }}
        </p>
        <hr>
        <h1 class="custom_label">Misc</h1>
        <br>
        <p>
            Cats or Dogs: {{ profile_user.profile.cats_or_dogs }}
            <br>
            Hobby: {{ profile_user.profile.hobby }}
            <br>
            Favourite Colour: {{ profile_user.profile.favourite_colour }}
        </p>
        <hr>
    </div>
    <div class="grid-70">
        <h1 class="custom_label">Bio</h1>
        <p></p>
            {{ profile_user.profile.bio|safe }}
    </div>
    <div class="footer_space">  

    </div>
</div>

{% if user.id == profile_user.id %}
<div class="button_track">
    <div class="btn_wrapper" id="btn_wrapper">
        <span class="circle_btn" id="circle_button">
            <a class="btn" href="{% url 'accounts:edit_profile' %}"><i class="material-icons md-48 md-light"
                    style="color:black;font-size:32px;margin-top:13px;">edit</i>
        </span>
    </div>      
</div>
{% endif %}
{% endblock %}

{% block javascript %}
<script type="text/javascript">
    $(document).ready(function () {
        $('#info_message').on('click', function () {
            $('#info_message').hide();
        });
    });
</script>

<script type="text/javascript">
    $(document).scroll(function () {
        checkOffset();
    });

    function checkOffset() {
        if ($('#circle_button').offset().top + $('#circle_button').height()
            >= $('#custom_footer').offset().top - 50)
            $('#circle_button').css('position', 'absolute');
        if ($(document).scrollTop() + window.innerHeight < $('#custom_footer').offset().top)
            $('#circle_button').css('position', 'fixed'); // restore when you scroll up
    }
</script>
{% endblock %}