accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'sign_in/$', views.sign_in, name='sign_in'),
    url(r'sign_up/$', views.sign_up, name='sign_up'),
    url(r'sign_out/$', views.sign_out, name='sign_out'),
    url(r'edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'profile/detail/(?P<user_pk>\d+)/$', views.profile, name='profile'),
    url(r'profile/change_password/$',
        views.change_password,
        name='change_password'),
    url(r'ajax/load-cities/$', views.load_cities, name='ajax_load_cities'),
]

project_7/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', views.home, name='home'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}
<div class="bounds circle--page">
  <div class="home-container">
    <div class="grid-100 centered">
      <h1>All About You</h1>
      <p>
        Show the world who you are. Easily display your name, show them your
        face, tell them a little about yourself - even your favourite colour.
      </p>
    </div>
  </div>

  <!-- CAROUSEL -->
  <div class="grid-100">
    <div class="slider-container">
      <div class="slider">
        {% for user in users %}
        <div class="slider_avatar_wrapper">
          <a href="{% url 'accounts:profile' user.pk %}">
            <img class="slider_avatar_circle" src="{{ user.profile.avatar.url }}" />
            <h3>{{ user.username }}</h3>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="home-container">
      <div class="grid-100 centered">
        <h1>It's Easy to Sign Up!</h1>
        <p>
          Create your profile now.
        </p>
        <a href="{% url 'accounts:sign_up' %}" class="button button-primary centered">Sign Up</a>
      </div>
    </div>
  
</div>
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css" />
<link rel="stylesheet" type="text/css" href="{% static 'css/slick-theme.css' %}" />
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'js/slick.js' %}"></script>

<script type="text/javascript">
  $(document).ready(function () {
    $('.slider').slick({
      arrows: false,
      autoplay: true,
      autoplaySpeed: 2000,
      adaptiveHeight: false,
      centerMode: true,
      centerPadding: '15px',

      dots: true,
      infinite: true,
      speed: 900,
      slidesToShow: 4,
      slidesToScroll: 4,
      responsive: [
        {
          breakpoint: 1024,
          settings: {
            slidesToShow: 3,
            slidesToScroll: 3,
            infinite: true,
            dots: true
          }
        },
        {
          breakpoint: 600,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 2
          }
        },
        {
          breakpoint: 480,
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1
          }
        }
        // You can unslick at a given breakpoint now by adding:
        // settings: "unslick"
        // instead of a settings object
      ]
    });

  });

</script>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Shrikhand&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Damion&display=swap" rel="stylesheet">


    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/global.css" %}">
    {% block css%}{% endblock %}

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript" src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>
    <!-- ICONS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
{% if messages %}
<div class="info_messages centered">
    {% for message in messages %}
    <p {% if message.tags %} class="{{ message.tags }}" {% endif %} id="info_message">{{ message }}</p>
    {% endfor %}
</div>
{% endif %}
<div class="alert centered" role="alert" id="alert"></div>

<body>
    <header class="circle--header">
        <div class="bounds">
            <div class="circle--fluid">
                <div class="circle--fluid--cell">
                    <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'home' %}">Circle</a>
                    </h1>
                </div>
                <div class="circle--fluid--cell circle--fluid--primary">
                    <nav>
                        <ul class="circle--inline">
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'accounts:profile' user_pk=user.id %}">My Profile</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                <div class="circle--fluid--cell circle--fluid--secondary">

                    <nav>
                        <ul class="circle--inline">
                            {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign In</a></li>
                            {% else %}
                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                            {% endif %}

                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <section class="custom_banner">
    </section>

    <div class="bounds circle--page">
        {% block body %}{% endblock %}
        {% block javascript %}
        <script type="text/javascript">
            $(document).ready(function () {
                $('#info_message').on('click', function () {
                    $('#info_message').hide();
                });
            });
        </script>
        {% endblock %}
    </div>

</body>
<footer class="custom_footer" id="custom_footer">
    <div class="bounds">
        <div class="grid-30">
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:profile' user_pk=user.id %}">My Profile</a></li>
                <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                {% else %}
                <li><a href="{% url 'accounts:sign_in' %}">Sign In</a></li>
                <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="grid-30">
            <ul>
                <li>About</li>
                <li>Contact</li>
            </ul>
        </div>
        <div class="grid-30">
            <ul>
                <li><a href="https://www.vecteezy.com/free-vector/owl">Owl Vectors by Vecteezy</a></li>
            </ul>          
        </div>
    </div>
    
</footer>

</html>